/* auto-generated by napi-rs */
export function levenshtein_similarity(a: string, b: string): number;
export function jaro_winkler_similarity(a: string, b: string): number;
export function hamming_similarity(a: string, b: string): number;
export function jaccard_similarity(a: string, b: string, n: number): number;
export function bm25_similarity(a: string, b: string): number;
export function tfidf_similarity(a: string, b: string): number;
export function clean_text(text: string): string;
