/* auto-generated by napi-rs */

export function levenshtein_distance(a: string, b: string): number;
export function levenshtein_similarity(a: string, b: string): number;
export function jaro_winkler_similarity(a: string, b: string): number;
export function hamming_distance(a: string, b: string): number;
export function hamming_similarity(a: string, b: string): number;
export function jaccard_similarity(a: string, b: string, n: number): number;
export function jaccard_bigram_similarity(a: string, b: string): number;
export function jaccard_trigram_similarity(a: string, b: string): number;
export function jaccard_word_similarity(a: string, b: string): number;
export function minhash_signature(text: string, shingle_size: number, num_hashes: number): number[];
export function minhash_similarity(a: string, b: string, shingle_size: number, num_hashes: number): number;
export function minhash_similarity_default(a: string, b: string): number;
export function simhash_fingerprint(text: string, shingle_size: number): number;
export function simhash_fingerprint_default(text: string): number;
export function simhash_similarity(a: string, b: string, shingle_size: number): number;
export function simhash_similarity_default(a: string, b: string): number;
export function bm25_similarity(a: string, b: string): number;
export function tfidf_similarity(a: string, b: string): number;
export function clean_text(text: string): string;
export function clean_text_stopwords(text: string): string;
