/* auto-generated by NAPI-RS */
/* eslint-disable */
/** BM25 similarity between two strings. */
export declare function bm25_similarity(a: string, b: string): number

/** Convenience: preprocess with defaults. */
export declare function clean_text(text: string): string

/** Convenience: preprocess and remove stopwords. */
export declare function clean_text_stopwords(text: string): string

/**
 * Hamming distance (raw differing character count).
 * Throws if strings have different lengths.
 */
export declare function hamming_distance(a: string, b: string): number

/**
 * Hamming similarity (normalized 0..1).
 * Throws if strings have different lengths.
 */
export declare function hamming_similarity(a: string, b: string): number

/** Jaccard similarity using bigrams (n=2). */
export declare function jaccard_bigram_similarity(a: string, b: string): number

/** Jaccard similarity with configurable n-gram size. */
export declare function jaccard_similarity(a: string, b: string, n: number): number

/** Jaccard similarity using trigrams (n=3). */
export declare function jaccard_trigram_similarity(a: string, b: string): number

/** Jaccard similarity at the word level. */
export declare function jaccard_word_similarity(a: string, b: string): number

/** Jaro-Winkler similarity. */
export declare function jaro_winkler_similarity(a: string, b: string): number

/** Levenshtein distance (raw edit count). */
export declare function levenshtein_distance(a: string, b: string): number

/** Levenshtein similarity (normalized 0..1). */
export declare function levenshtein_similarity(a: string, b: string): number

/** MinHash signature as array of numbers. */
export declare function minhash_signature(text: string, shingleSize: number, numHashes: number): Array<number>

/** MinHash similarity between two strings. */
export declare function minhash_similarity(a: string, b: string, shingleSize: number, numHashes: number): number

/** MinHash similarity with default parameters (shingle=3, hashes=128). */
export declare function minhash_similarity_default(a: string, b: string): number

/** SimHash 64-bit fingerprint as a number. */
export declare function simhash_fingerprint(text: string, shingleSize: number): number

/** SimHash 64-bit fingerprint with default shingle size (4). */
export declare function simhash_fingerprint_default(text: string): number

/** SimHash similarity between two strings. */
export declare function simhash_similarity(a: string, b: string, shingleSize: number): number

/** SimHash similarity with default shingle size (4). */
export declare function simhash_similarity_default(a: string, b: string): number

/** TF-IDF + Cosine similarity between two strings. */
export declare function tfidf_similarity(a: string, b: string): number
