/* eslint-disable */
/* auto-generated by napi-rs — do not edit */

const { existsSync, readFileSync } = require('fs');
const { join } = require('path');

const { platform, arch } = process;

let nativeBinding = null;
let localFileExisted = false;
let loadError = null;

function isMusl() {
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process')
        .execSync('which ldd')
        .toString()
        .trim();
      return readFileSync(lddPath, 'utf8').includes('musl');
    } catch (_) {
      return true;
    }
  } else {
    const report = process.report.getReport();
    const sharedObjects = (report && report.sharedObjects) || [];
    return sharedObjects.some((s) => s.includes('libc.musl') || s.includes('ld-musl'));
  }
}

switch (platform) {
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'simi.win32-x64-msvc.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./simi.win32-x64-msvc.node');
          } else {
            nativeBinding = require('@siktec-lab/simi-win32-x64-msvc');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`);
    }
    break;
  case 'darwin':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'simi.darwin-x64.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./simi.darwin-x64.node');
          } else {
            nativeBinding = require('@siktec-lab/simi-darwin-x64');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'simi.darwin-arm64.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./simi.darwin-arm64.node');
          } else {
            nativeBinding = require('@siktec-lab/simi-darwin-arm64');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`);
    }
    break;
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'simi.linux-x64-musl.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./simi.linux-x64-musl.node');
            } else {
              nativeBinding = require('@siktec-lab/simi-linux-x64-musl');
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'simi.linux-x64-gnu.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./simi.linux-x64-gnu.node');
            } else {
              nativeBinding = require('@siktec-lab/simi-linux-x64-gnu');
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'simi.linux-arm64-musl.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./simi.linux-arm64-musl.node');
            } else {
              nativeBinding = require('@siktec-lab/simi-linux-arm64-musl');
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'simi.linux-arm64-gnu.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./simi.linux-arm64-gnu.node');
            } else {
              nativeBinding = require('@siktec-lab/simi-linux-arm64-gnu');
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`);
    }
    break;
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`);
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError;
  }
  throw new Error('Failed to load native binding');
}

const {
  levenshtein_distance,
  levenshtein_similarity,
  jaro_winkler_similarity,
  hamming_distance,
  hamming_similarity,
  jaccard_similarity,
  jaccard_bigram_similarity,
  jaccard_trigram_similarity,
  jaccard_word_similarity,
  minhash_signature,
  minhash_similarity,
  minhash_similarity_default,
  simhash_fingerprint,
  simhash_fingerprint_default,
  simhash_similarity,
  simhash_similarity_default,
  bm25_similarity,
  tfidf_similarity,
  clean_text,
  clean_text_stopwords,
} = nativeBinding;

module.exports.levenshtein_distance = levenshtein_distance;
module.exports.levenshtein_similarity = levenshtein_similarity;
module.exports.jaro_winkler_similarity = jaro_winkler_similarity;
module.exports.hamming_distance = hamming_distance;
module.exports.hamming_similarity = hamming_similarity;
module.exports.jaccard_similarity = jaccard_similarity;
module.exports.jaccard_bigram_similarity = jaccard_bigram_similarity;
module.exports.jaccard_trigram_similarity = jaccard_trigram_similarity;
module.exports.jaccard_word_similarity = jaccard_word_similarity;
module.exports.minhash_signature = minhash_signature;
module.exports.minhash_similarity = minhash_similarity;
module.exports.minhash_similarity_default = minhash_similarity_default;
module.exports.simhash_fingerprint = simhash_fingerprint;
module.exports.simhash_fingerprint_default = simhash_fingerprint_default;
module.exports.simhash_similarity = simhash_similarity;
module.exports.simhash_similarity_default = simhash_similarity_default;
module.exports.bm25_similarity = bm25_similarity;
module.exports.tfidf_similarity = tfidf_similarity;
module.exports.clean_text = clean_text;
module.exports.clean_text_stopwords = clean_text_stopwords;
